
language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - .cache
    - node_modules
install:
  - yarn install
script:
  - yarn run deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 3af2ac1680854d783a8f8e5178e0f6eb14c01c0e
  local-dir: public
  on:
    branch: master