backend:
  name: github
  repo: ShawonAshraf/new-blog

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content
    slug: "{{date}}-{{dir}}/index.md"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "dir", label: "Directory", widget: "string" }
      - { name: "path", label: "Path", widget: "string" }
      - { name: "date", label: "Date", widget: "date", format: "YYYY-MM-DD" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "excerpt", label: "Excerpt", widget: "text" }
      - { name: "cover", label: "Cover", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }