---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: directory
  path: src/images
  label: cover-images
  create: documents
  match: "**/*"
- type: directory
  path: content
  label: posts
  create: all
  match: "**/*"
upload_dir: src/images
public_path: src/images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: gatsby develop -H 0.0.0.0 -p 8080
  preview_command: gatsby build
